### ISSUE TITLE
no rc input filtering/smoothing?

### ISSUE THREAD

**Issue by marcelkk** [flyduino/kissfcv2-firmware#10]
I got a problem with my Kiss quad using crossfireV2 or crossfire shot (no difference).
In the crossfire 50 Hz mode, the transients of the rc/setpoint signals are so high, i can hear them in my motors.
That means, especially with idle-throttle i can hear the 50 Hz peaks really strong. Normally its difficult to hear, because crossfire switch from 150 Hz to 50 Hz in a distance where i can't hear my quad enough. But i can feel it, and that isn't nice (less smooth than in 150 Hz mode). I know, especially the D-Term boosts this, so i tried really low values for D and P. Is there anything wrong in my setup? I can't imagine that this is normal...
Enclosed two Pictures from a blackbox-log, showing the signal curves.
Thanks and greetings from Germany

<img width="1188" alt="crsf1" src="https://user-images.githubusercontent.com/65137502/96648897-62178a80-1330-11eb-8e88-ad4ff80a75cc.png">
<img width="1187" alt="crsf2" src="https://user-images.githubusercontent.com/65137502/96648903-6643a800-1330-11eb-9d3c-54e88180fdfb.png">

**Comment by fedorcomander** [comment]
kiss doesnt process rc input in any way, so your setup is fine.

**Comment by marcelkk** [comment]
thank you
