### ISSUE TITLE
SmartAudio V2.1

### ISSUE THREAD

**Issue by shadeIess** [flyduino/kissfcv2-firmware#3]
The TBS Unify Evo VTX doesn'T work with Kiss FC (v2).
Evo uses the new SmartAudio V2.1 protocol which apparently isn't compatible.
It would be great if you could implement SmartAudio V2.1 support!
Thank you!

**Comment by J-SKINS** [comment]
Does the Unify 32 HV run the same protocol as the EVO?

Semper Fi,

[cid:FDCCB102-BA8B-4860-AFD4-2B7CA2D99AFD@hsd1.fl.comcast.net]

  CGC045443 | CGC1517439  | CGC060924

Jud Tucker | V.P.
    Established 1989

15 Paradise Plaza, Suite 200
Sarasota, FL 34239
941.650.7789 mobile DIRECT Line
941.371.7500 Ext.# 303 Off •<http://www.5tco.com/>
941.371.7550 Fax<http://www.5tco.com/>
jtucker@5tco.com<mailto:jtucker@5tco.com>

Follow us on Twitter to see our Metal Wall Panel Installations throughout Florida:

FIVE-T-CO on Twitter<http://twitter.com/5tco?lang=en>

https://www.youtube.com/channel/UCtPt7blSus8gGj6cfOow3tA

[cid:042FC107-C239-4131-9D5E-71B2CC817B65@hsd1.fl.comcast.net][cid:CFE2EC36-FB80-418E-8D03-EFC44A5E734B@hsd1.fl.comcast.net]

On Jun 10, 2019, at 5:49 AM, shadeIess <notifications@github.com<mailto:notifications@github.com>> wrote:


The TBS Unify Evo VTX doesn'T work with Kiss FC (v2).
Evo uses the new SmartAudio V2.1 protocol which apparently isn't compatible.
It would be great if you could implement SmartAudio V2.1 support!
Thank you!

**Comment by shadeIess** [comment]
I believe it uses SmartAudio v2.0

**Comment by J-SKINS** [comment]
Does 2.0 work with KISS FCV2?  I just bought (2) UNIFY 32 HV ….. crap, I hope it works ok.


Semper Fi,

[cid:FDCCB102-BA8B-4860-AFD4-2B7CA2D99AFD@hsd1.fl.comcast.net]

  CGC045443 | CGC1517439  | CGC060924

Jud Tucker | V.P.
    Established 1989

15 Paradise Plaza, Suite 200
Sarasota, FL 34239
941.650.7789 mobile DIRECT Line
941.371.7500 Ext.# 303 Off •<http://www.5tco.com/>
941.371.7550 Fax<http://www.5tco.com/>
jtucker@5tco.com<mailto:jtucker@5tco.com>

Follow us on Twitter to see our Metal Wall Panel Installations throughout Florida:

FIVE-T-CO on Twitter<http://twitter.com/5tco?lang=en>

https://www.youtube.com/channel/UCtPt7blSus8gGj6cfOow3tA

[cid:042FC107-C239-4131-9D5E-71B2CC817B65@hsd1.fl.comcast.net][cid:CFE2EC36-FB80-418E-8D03-EFC44A5E734B@hsd1.fl.comcast.net]

On Jun 11, 2019, at 9:03 AM, shadeIess <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe it uses SmartAudio v2.0

**Comment by shadeIess** [comment]
I'm not sure if yours is affected also, here on the betaflight github issue, they talk about "TBS Unify HV Race v2" -> https://github.com/betaflight/betaflight/issues/7336

On betaflight, they already implemented it, hopefully, the Kiss devs do so, too.

**Comment by J-SKINS** [comment]
Thank you for the info man.  I appreciate it.

Semper Fi,

[cid:FDCCB102-BA8B-4860-AFD4-2B7CA2D99AFD@hsd1.fl.comcast.net]

  CGC045443 | CGC1517439  | CGC060924

Jud Tucker | V.P.
    Established 1989

15 Paradise Plaza, Suite 200
Sarasota, FL 34239
941.650.7789 mobile DIRECT Line
941.371.7500 Ext.# 303 Off •<http://www.5tco.com/>
941.371.7550 Fax<http://www.5tco.com/>
jtucker@5tco.com<mailto:jtucker@5tco.com>

Follow us on Twitter to see our Metal Wall Panel Installations throughout Florida:

FIVE-T-CO on Twitter<http://twitter.com/5tco?lang=en>

https://www.youtube.com/channel/UCtPt7blSus8gGj6cfOow3tA

[cid:042FC107-C239-4131-9D5E-71B2CC817B65@hsd1.fl.comcast.net][cid:CFE2EC36-FB80-418E-8D03-EFC44A5E734B@hsd1.fl.comcast.net]

On Jun 11, 2019, at 3:49 PM, shadeIess <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure if yours is affected also, here on the betaflight github issue, they talk about "TBS Unify HV Race v2" -> betaflight/betaflight#7336<https://github.com/betaflight/betaflight/issues/7336>

On betaflight, they already implemented it, hopefully, the Kiss devs do so, too.

**Comment by 01ivr3** [comment]
Do I have it right that SmartAudio v2.1 is not yet supported in Betaflight v4.0.3?! 

I just spent the past hour trying everything I could think of to get smart SmartAudio working between a new TBS Unify Pro32 HV with CRSF Rx1 (SA) connected to T6 on an RDQ Bardwell F4 v2 FC. Nothing seems to work 😢
