### ISSUE TITLE
Tiny's LEDs Real Pit for team racing?

### ISSUE THREAD

**Issue by BikeGuy1992** [flyduino/kissfcv2-firmware#4]
Is there going to be any sort of firmware update to be able to run a Tiny's LEDs Rral Pit for team racing any time soon? Feeling pretty neglected with five racing rigs all setup on KISS and not having some sort of firmware update compared to BF and FL1 which have had it for months now.

**Comment by lichtl** [comment]
Available i 1.3RC39b
